services:
  api-getawey:
    build: ./api-getawey
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api-getawey:/app
    env_file:
      - ./api-getawey/.env 
    depends_on:
      - auth
      - tasks
    networks:
      - app-network

  auth:
    build: ./auth
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    volumes:
      - ./auth:/app
    env_file:
      - ./auth/.env 
    networks:
      - app-network

  tasks:
    build: ./tasks
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - tasks-db
    volumes:
      - ./tasks:/app
    env_file:
      - ./tasks/.env 
    networks:
      - app-network

  notifications:
    build: ./notifications
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ./notifications:/app
    env_file:
      - ./notifications/.env 
    networks:
      - app-network

  logs:
    build: ./logs
    restart: always
    depends_on:
      - logs-db
    ports:
      - "3004:3004"
    volumes:
      - ./logs:/app
    env_file:
      - ./logs/.env 
    networks:
      - app-network

  auth-db:
    image: mongo:latest
    container_name: auth-db
    restart: always
    ports:
      - "27018:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./auth-db:/data/db

  logs-db:
    image: mongo:latest
    container_name: logs-db
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./logs-db:/data/db

  tasks-db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tasks
    networks:
      - app-network
    volumes:
      - ./tasks-db:/var/lib/postgresql/data
      
  rabbitmq:
    container_name: rabbitmq-taskflow
    image: rabbitmq:3.12.4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
  
  redis:
    container_name: redis-taskflow
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data

networks:
  app-network:
    driver: bridge
